# Generated by Django 5.1 on 2024-09-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField()),
                ('calification', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_calification', models.IntegerField()),
                ('image_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField()),
                ('recomendaciones', models.TextField()),
                ('images', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
