def obtenerClubster(cluster):
    images = ""
    if cluster == 1:
        images = "CasaGabo.jpg", "PaseoDeLasArmas.jpg","PaseoDeLosCañones.jpg", "CapillaLaDivinaPastora.jpg","Catedral.jpg","FranciscoElHombre.jpg","LosEmbarradores.jpg","PilanderasDelCarnavalDeRiohacha..jpg","Artesanias4.jpg","Muelle.png","CallejosDeLosCapuchinos.jpg","Cultura.jpg"
    elif cluster == 2:
        images =  "Artesanias.jpg","EsculturaGénesis.jpg","EsculturaJosePrudencioPadilla.jpg","ElPalabrero.jpg","ElPoporo.jpg", "EsculturaRelacionEntreElCosmosLaNaturalezaYElHombre.jpg","EsculturaNicolasDeFederman.jpg","FranciscoElHombre.jpg","HombreIndígena.jpg","Identidad.jpg","LosEmbarradores.jpg","MariposasAmarillas.jpg","MujerIndígena.jpg","PilanderasDelCarnavalDeRiohacha..jpg", "Muelle.png","CallejonDeLosCapuchinos.jpg"
    elif cluster == 3:
        images = "ElPoporo.jpg", "EsculturaRelacionEntreElCosmosLaNaturalezaYElHombre.jpg","EsculturaGénesis.jpg","EsculturaJosePrudencioPadilla.jpg","EsculturaNicolasDeFederman.jpg","FranciscoElHombre.jpg","HombreIndígena.jpg","Identidad.jpg","ElPalabrero.jpg","LosEmbarradores.jpg","MariposasAmarillas.jpg","MujerIndígena.jpg","PilanderasDelCarnavalDeRiohacha..jpg", "CasaGabo.jpg", "PaseoDeLasArmas.jpg","PaseoDeLosCañones.jpg", "CapillaLaDivinaPastora.jpg","Catedral.jpg","Artesanias4.jpg","Muelle.png","CallejonDeLosCapuchinos.jpg"
    elif cluster == 4:
        images = "EsculturaGénesis.jpg","ElPalabrero.jpg","ElPoporo.jpg", "EsculturaRelacionEntreElCosmosLaNaturalezaYElHombre.jpg","EsculturaNicolasDeFederman.jpg","EsculturaJosePrudencioPadilla.jpg","FranciscoElHombre.jpg","HombreIndígena.jpg","Identidad.jpg","LosEmbarradores.jpg","MariposasAmarillas.jpg","MujerIndígena.jpg","PilanderasDelCarnavalDeRiohacha..jpg", "Artesanias3.jpg","Muelle.png","CallejonDeLosCapuchinos.jpg","Cultura.jpg"
    elif cluster == 5:
        images = "ElPoporo.jpg","EsculturaJosePrudencioPadilla.jpg","EsculturaRelacionEntreElCosmosLaNaturalezaYElHombre.jpg","EsculturaGénesis.jpg","EsculturaNicolasDeFederman.jpg","FranciscoElHombre.jpg","HombreIndígena.jpg","Identidad.jpg","ElPalabrero.jpg","LosEmbarradores.jpg","MariposasAmarillas.jpg","MujerIndígena.jpg","PilanderasDelCarnavalDeRiohacha..jpg", "CasaGabo.jpg", "PaseoDeLasArmas.jpg","PaseoDeLosCañones.jpg","CapillaLaDivinaPastora.jpg","Catedral.jpg","Artesanias4.jpg"
    elif cluster == 6:
        images = "ElPalabrero.jpg","EsculturaJosePrudencioPadilla.jpg","ElPoporo.jpg","EsculturaGénesis.jpg", "EsculturaRelacionEntreElCosmosLaNaturalezaYElHombre.jpg","FranciscoElHombre.jpg","HombreIndígena.jpg","Identidad.jpg","EsculturaNicolasDeFederman.jpg","LosEmbarradores.jpg","MariposasAmarillas.jpg","MujerIndígena.jpg","PilanderasDelCarnavalDeRiohacha..jpg","CasaGabo.jpg", "PaseoDeLasArmas.jpg","PaseoDeLosCañones.jpg", "Artesanias2.jpg","CapillaLaDivinaPastora.jpg","Catedral.jpg","Muelle.png","CallejonDeLosCapuchinos.jpg"
    elif cluster == 7:
        images = "HombreIndígena.jpg","EsculturaNicolasDeFederman.jpg","ElPalabrero.jpg","ElPoporo.jpg","EsculturaGénesis.jpg","Identidad.jpg", "EsculturaRelacionEntreElCosmosLaNaturalezaYElHombre.jpg","FranciscoElHombre.jpg","EsculturaJosePrudencioPadilla.jpg","LosEmbarradores.jpg","MariposasAmarillas.jpg","MujerIndígena.jpg","PilanderasDelCarnavalDeRiohacha..jpg", "Artesanias2.jpg","Artesanias1.jpg","Artesanias.jpg"
    elif cluster == 8:
        images = "Artesanias2.jpg", "Artesanias1.jpg","Artesanias4.jpg","Artesanias.jpg","Artesanias3.jpg", "CallejosDeLosCapuchinos.jpg", "Muelle.png"
    elif cluster == 9:
        images = "EsculturaNicolasDeFederman.jpg","ElPalabrero.jpg","ElPoporo.jpg","EsculturaGénesis.jpg", "EsculturaJosePrudencioPadilla.jpg","EsculturaRelacionEntreElCosmosLaNaturalezaYElHombre.jpg","FranciscoElHombre.jpg","HombreIndígena.jpg","Identidad.jpg","LosEmbarradores.jpg","MariposasAmarillas.jpg","MujerIndígena.jpg","PilanderasDelCarnavalDeRiohacha..jpg","Artesanias.jpg","Muelle.png","CallejosDeLosCapuchinos.jpg","Cultura.jpg"
    elif cluster == 0:
        images = "ElPoporo.jpg", "EsculturaRelacionEntreElCosmosLaNaturalezaYElHombre.jpg","EsculturaGénesis.jpg","EsculturaNicolasDeFederman.jpg","FranciscoElHombre.jpg","EsculturaJosePrudencioPadilla.jpg","HombreIndígena.jpg","Identidad.jpg","ElPalabrero.jpg","LosEmbarradores.jpg","MariposasAmarillas.jpg","MujerIndígena.jpg","PilanderasDelCarnavalDeRiohacha..jpg","CasaGabo.jpg", "PaseoDeLasArmas.jpg","PaseoDeLosCañones.jpg", "Artesanias2.jpg","CapillaLaDivinaPastora.jpg","Catedral.jpg","Artesanias1.jpg","CallejosDeLosCapuchinos.jpg", "Muelle.png"
    return images